### ISSUE TITLE
Wire I/O problems

### ISSUE THREAD

**Issue by Jeffman12** [ACF-Gmod/ACF#4]
[Pasted from FP thread]
So, now "Ready"(To fire) seems faulty, I'm using a 20mm AC to do some testing. It reports as 1 even when the weapon is not loaded.
I need to hold down the button to set ammo as active for it to fire more than one shot, and the number of shots it will fire is set to 30, but it only depletes if I don't let go of the mouse button at all before all 30 deplete. I've taken to labeling that latter as "heat" instead of rounds left, as it seems to work better under that description.

Actually, scratch that last part, this is sort of weird: I need to designate an ammo as active for the weapon to load it, this makes sense the first time, but as is makes having a reload key unnecessary, but as is, the reload key doesn't seem to work, so to fire repeatedly, I must hold down the button to designate an ammo type as active if I wish to sustain fire. Good thing I wired it to mouse 2.

I started with a basic testing setup

Chair, pod controller, gun, ammo crate.
The gun is set to a display to show when it can fire and how many rounds are loaded, allegedly 30, but I can't fire them in sequence without holding down mouse2 while clicking/holding down mouse1 to fire.

**Comment by Kafouille** [comment]
Active input is a constant input, not a momentary one. Working as intended

**Comment by Jeffman12** [comment]
Well, okay, that's easy enough to work with. But that doesn't address the rest of the issue. As far as I can see the "Reload" input is completely pointless, I never need to use it, setting an ammo as active loads every weapon I've tried automatically after the firing cycle completes. This is the same for Howitzers, Machine Guns, and Cannons alike.

If something is intended to not have function, it should be removed.

The weapon output "Ready", is misleading, and as it currently operates requires twice as much screen space as it should, using simple bool display methods typically means screen space won't be at a premium, but that's not the only issue.

As is; first you must indicate that the weapon can fire, and then you must have a display stating if it's loaded or how much is loaded. I can see how this may help in diagnostics, but the only thing it really tells you is that your ammo supply is mis-configured or gone, the presence or lack of an ammo storage unit should be indication enough.

The only thing that should be modified in this case is what determines whether a weapon is ready to fire. It should be cycle time as well as whether the weapon is loaded.

**Comment by Kafouille** [comment]
The reload input is there because you may want to unload the round currently in the chamber with large weapons without expending the round, as removing the Active input from a crate will not unload the round. The Ready output should take into account reload time. If it doesn't please submit reproduction steps for that issue in a new bug report.
